services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    env_file:
      - .env.example
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
