---
# https://gethomepage.dev/configs/settings/

# favicon: https://akmalov.com/img/favicon.ico
title: Lab Homepage
# headerStyle: clean
bookmarksStyle: icons
theme: dark
color: slate
hideVersion: true

background: 
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: md
  saturate: 50
  brightness: 50
  opacity: 50

useEqualHeights: true

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true

layout:
  bookmarks1:
    header: false
    style: column
  bookmarks2:
    header: false
    style: column
  bookmarks3:
    header: false
    style: column
  Services:
    header: true
    style: row
    columns: 4
  Infrastructure:
    header: true
    style: row
    columns: 4
  Monitoring:
    header: true
    style: row
    columns: 4
  Storage:
    header: true
    style: row
    columns: 4
  Media:
    header: true
    style: row
    columns: 4

